version: '3.9'

networks:
  app_network:

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-app
    volumes:
      - ./server/resources/data:/resources/data
      - ./server/resources/logs:/resources/logs
    ports:
      - "8080:8080"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - app_network

  client:
    build:
      context: ./clients/golang
      dockerfile: Dockerfile
    container_name: client-app
    ports:
      - "3000:3000"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - ENV=production
    networks:
      - app_network